apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/load-balancer-source-ranges: 16.248.4.0/24, 159.196.169.106/32
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - targetPort: {{ .Values.frontend.service.targetPort }}
      port: {{ .Values.frontend.service.port }}
      name: {{ .Values.frontend.service.name }}
  selector:
    app: {{ .Values.frontend.name }}
